const express = require("express");
const postController = require("../controllers/post.controller");
const router = express.Router();
router.use(express.json());
router.get("/:userId", postController.getPostsByUserId);
router.get("/", postController.getPost);
router.get("/status/public", postController.getPostWithisPublicTrue);
router.post("/:userId", postController.createPostByUserId);
router.get("/:userId", postController.updatePostByPostId);
module.exports = router;
